### ISSUE TITLE
Show symbols of backtraces

### ISSUE THREAD

**Issue by nielx** [nielx/rust#2]
Rust has internals to show the backtrace after a panic!. The symbols are not showing, unfortunately.

**Update on 25-10-2018:**
Preliminary investigation:
- ​libpanic_unwind
- libstd/sys_common/backtrace.rs 
​- libstd/sys/unix/backtrace 
​- libstd/sys_common/gnu/backtrace.rs 
The system for resolving symbols is quite elaborate, but it seems that on Haiku the ​libbacktrace is used. It would be good to start testing there.

**Update on 24-06-2018:**
Tested so far:
- The combination on Haiku could be libunwind for getting the stack traces, and dladdr to get the symbols. 
- When I write my own little cpp to test these functions, everything works out great. Libunwind finds the proper stack trace, and dladdr finds the symbol names. 
- When I switch over to a rustc compiled program things go awry. All the symbol names are set to _init. 
- I checked rustc's libc: the definitions for Dl_info and dladdr are good. 
- I checked the ip-addresses of the stack trace: they match what I find in debugger, so libunwind seems to be working just fine. 
- These ip addresses are also being fed to dladdr, but there it goes awry: the only symbol name that is returned is _init. 
- Hypothesis: the output of rustc is different in such a way that the symbol names cannot be found by the method of dladdr. 

**Update on 24-06-2018:**
I figured it out. The problem is exactly the issue about local symbol tables that is mentioned in the ​rust source. I have verified this by manually adding the -export-dynamic to the link flags. Then the symbol names are available. 
Thus in short: we cannot use dladdr on Haiku to resolve symbols.

**Comment by leavengood** [comment]
As you may or may not be aware, I am interested in helping out some on Rust for Haiku.

With that said, you don't think there are things we could fix on the Haiku side to get this working? Which I guess would mean fixing our dladdr to work like other platforms?

If you have some minimal test case for this that might help.

**Comment by nielx** [comment]
Hi Ryan, I appreciate the help.

It's been a while since I looked at this problem. Your suggestion of making our dladdr work like MacOS X could work. Alternatively it might be interesting to look into why libbacktrace does not work on Haiku the way it does on other platforms. See https://github.com/alexcrichton/backtrace-rs/

**Comment by nielx** [comment]
Upstream patch: https://github.com/rust-lang/backtrace-rs/pull/411

**Comment by nielx** [comment]
Fixed in libbacktrace 0.3.59
