### ISSUE TITLE
RustC crashes when compiling

### ISSUE THREAD

**Issue by mauritslamers** [nielx/rust#8]
When running Rust 1.28.0-1 under Haiku, a crash report is generated. ([rustc-1232-debug-27-09-2018-10-49-44-report.txt](https://github.com/nielx/rust/files/2427241/rustc-1232-debug-27-09-2018-10-49-44-report.txt))
Interestingly enough, after this crash, it managed to continue compiling.

However, after a restart of the system, I get a total freeze a few seconds in when I am trying to use cargo to install crates. It jumps to 100% of one CPU core, and stays there, making the system completely non-responsive.

**Comment by nielx** [comment]
I have not seen this behaviour recently with newer Rust versions on Haiku R1 beta 2.
